# Generated by Django 5.0.1 on 2024-01-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
