# Generated by Django 5.0.1 on 2024-02-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='subject_id',
        ),
    ]
