# Generated by Django 5.0.1 on 2024-02-03 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_course_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='year',
            new_name='sem',
        ),
    ]
