# Generated by Django 5.0.1 on 2024-02-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course_id',
        ),
        migrations.AddField(
            model_name='subject',
            name='course_id',
            field=models.ManyToManyField(related_name='course_subjects', to='members.course'),
        ),
    ]
