# Generated by Django 5.0.1 on 2024-02-03 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_year_course_sem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='section',
        ),
    ]
