# Generated by Django 5.0.1 on 2024-02-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_subject_course_id_subject_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
