# Generated by Django 5.0.1 on 2024-02-03 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='members.course'),
        ),
    ]
