# Generated by Django 5.0.1 on 2024-02-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='session_end_year',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='session_start_year',
            field=models.CharField(max_length=5),
        ),
    ]
